Style/LineLength:
  Max: 120
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/EmptyLinesAroundBody:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
